### PR TITLE
Fix confirmation callback translation

### PR DESCRIPTION
**Pull request by RobinVanhove**
This PR should resolve FORGEROCK-328.

It's still WIP, I need to test it more.

### CODE REVIEW

**Comment by RobinVanhove** [comment]
This is based on a fork of the tag 7.4.0.

**Comment by RobinVanhove** [comment]
This has been tested now. Will this be merged? Or will there be an other solution for the issue?

**Comment by mwong7861** [comment]
@RobinVanhove Can I ask what the use case is for adding the localization here? Confirmation callbacks can be localized in AM. For example, adding a message node to a journey allows you to set locales/text for the languages you want to support

**Comment by RobinVanhove** [comment]
Hi @mwong7861 As far I know there is not always a documented way translate messages from certain nodes. For example we want to use the 'OATH Token Verifier' which creates a ConfirmationCallback.
In the forgerock platform ui docs[1] it is stated that we should be able to use the overrides. But without this fix it will not work.
So we contacted FR support (ticket #104965) and they confirmed that this is a bug with jira ticket FORGEROCK-328.

Because there is no solution provided for us I've implemented this fix myself. If it is wrong or there is a better solution please let me know.

[1]: https://backstage.forgerock.com/docs/platform/7.3/platform-setup-guide/localize-enduser-login-uis.html

**Pull request closed without merging**
